In [2]:
list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]


In [4]:
list1

['apple', 'banana', 'cherry']

In [6]:
list2

[1, 5, 7, 9, 3]

In [7]:
list3

[True, False, False]

In [8]:
List_A = [1, 2, 3, 4, 5]
List_B = [11, 12, 13, 14, 15]
List_A * List_B

TypeError: ignored

In [9]:
import numpy as np
A = np.array(List_A)
B = np.array(List_B)


In [12]:
print(A)
print(B)
print(A*B)
print(A*2)
print(A*2)
print(A+A)
print(A+B)

[1 2 3 4 5]
[11 12 13 14 15]
[11 24 39 56 75]
[ 2  4  6  8 10]
[ 2  4  6  8 10]
[ 2  4  6  8 10]
[12 14 16 18 20]


Nested List

In [13]:
NL = [[1,2], [3,4], [5,6], [7,8],[9,10]]
NL

[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]

Nested List with NumPy

In [14]:
NL1 = np.array(NL)
NL1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [54]:
my_array = [[1,4,5,6], [7,8,9,10], [11,12,14,16]]
my_array_np = np.array(my_array)
my_array_np

array([[ 1,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 14, 16]])

In [15]:
[[1,4,5,6], [7,8,9,10], [11,12,14,16]]

[[1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16]]

NumPy Arange

In [18]:
np.arange(0,5) #array with evenly spaced number from 0 to 5 (excluding 5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(0,16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
np.arange(0,16,2) #array with a 2 step size 

array([ 0,  2,  4,  6,  8, 10, 12, 14])

Zeros and Ones

In [22]:
np.zeros(1)

array([0.])

In [23]:
np.zeros(2)

array([0., 0.])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

4x4 matrix of zeros

In [25]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

4x15 matrix of zeros

In [26]:
np.zeros((4,15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Converting floats to integers

In [27]:
np.zeros((4,15), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Arrays with ones (the same way as before)

In [29]:
np.ones(4)

array([1., 1., 1., 1.])

In [30]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

**Linspace** - evenly spaced numbers over a specified interval

In [31]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [32]:
np.linspace(0,20,20) #increasing the number of evenly spaced numbers 

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

**Eye** - identity matrix

In [33]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [34]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

**Rand** - createing random number arrays

In [36]:
np.random.rand(3)

array([0.597044  , 0.07253127, 0.03422048])

In [37]:
np.random.rand(3) #after runnig the same line again, results will be different

array([0.76301716, 0.1695642 , 0.81485222])

In [38]:
np.random.rand(2)

array([0.51038544, 0.02606615])

In [39]:
np.random.rand(2,3)

array([[0.38641935, 0.81843622, 0.49263583],
       [0.68654087, 0.9246131 , 0.03910952]])

**Randint** - random integers from low (inclusive) to high (exclusive)

In [40]:
np.random.randint(0,100)

47

In [41]:
np.random.randint(0,200,15)

array([ 85, 163,  17, 199, 113, 180, 135,  35,  41, 140,  92,  58,  57,
       167,  43])

In [42]:
np.random.randint(0,200,(3,5))

array([[ 29,  49,  73, 158, 168],
       [101,  27, 100, 118,  87],
       [ 72,  72, 117, 125, 192]])

**Reshape** - array containing the same data with a new shape

In [44]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
arr.shape

(25,)

In [46]:
arr.reshape(5,5) #it won't affect the original array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

**max, min, argmax, argmin**

In [48]:
arr.max() #max value in array

24

In [49]:
arr.min()

0

In [50]:
arr.argmax()

24

In [51]:
arr.argmin()

0

**Dtype** - finding data type of the object in the array

In [52]:
arr.dtype

dtype('int64')